/* eslint-disable import/no-anonymous-default-export */
export default {
	GET_GAME_DATA_REQUEST: 'GET_GAME_DATA_REQUEST',
	GET_GAME_DATA_SUCCESS: 'GET_GAME_DATA_SUCCESS',
	GET_GAME_DATA_FAILURE: 'GET_GAME_DATA_FAILURE',
	RESET_GAME_DATA_STATE: 'RESET_GAME_DATA_STATE'
}
